### ISSUE TITLE
First app start takes very long

### ISSUE THREAD

**Issue by cherry-wave** [adrielcafe/NMSAlphabetAndroidApp#2]
I don't know if this is just a development issue but after the app is deployed on the phone and started (you can already see a dark gray screen), it takes a very long time for the login screen to show up.

If I close the app and start it again, it is ok.

**Comment by adrielcafe** [comment]
Very odd, when the app starts for the first time it "does nothing" in the first 15 seconds

![captura de tela 2016-05-02 as 16 28 57](https://cloud.githubusercontent.com/assets/2512298/14965323/38a6f708-1083-11e6-8c86-3450d7f78f3e.png)

I'll investigate further

**Comment by adrielcafe** [comment]
Okay, found where the problem is.
Android Studio 2.0+ has the [Instant Run](http://developer.android.com/intl/pt-br/tools/building/building-studio.html#instant-run) feature:

> Introduced in Android Studio 2.0, Instant Run is a behavior for the Run  and Debug  commands that significantly reduces the time between updates to your app. Although **your first build may take longer to complete**, Instant Run pushes subsequent updates to your app without building a new APK, so changes are visible much more quickly.

To disable Instant Run go to Settings > Build, Execution, Deployment > Instant Run and disable the first option.
![captura de tela 2016-05-02 as 16 46 37](https://cloud.githubusercontent.com/assets/2512298/14965958/95cced7c-1086-11e6-9904-f9b3226fe49c.png)

**Tip**: Even if the the first build take too long, the next build will be far more fast with Instant Run. So It's good keep it enabled.

**Comment by cherry-wave** [comment]
OK thanks =)
